### ISSUE TITLE
Black images when rendering SVG

### ISSUE THREAD

**Issue by lferro9000** [pdepend/pdepend#256]
Hi,

When i render the images with:

pdepend --jdepend-xml=./build/logs/jdepend.xml --jdepend-chart=dependencies.svg --overview-pyramid=overview-pyramid.svg app/src

pdepend --jdepend-xml=./build/logs/jdepend.xml --jdepend-chart=dependencies.png --overview-pyramid=overview-pyramid.png app/src

The svg do show on inkscape, firefox, chrome and safari on Mac OS X 10.11.4 as black.

On several versions before, on both chrome and safari, they would show as the png, with color.

I've searched and found out that some browsers where "cutting corners" when implementing the svg standard with regard on how to handle the lines / areas and the thickness / colors.

This looks to have being fixed on all current renders of svg on Mac OS, however, libraries like pdepend are still generating incorrect svg images.

[overview-pyramid.zip](https://github.com/pdepend/pdepend/files/263092/overview-pyramid.zip)

**Comment by vbashkirtsev** [comment]
I found that this problem is caused by introduction of Content-Security-Policy headers. By default they are restrictive (ie if you open file locally it will not allow certain features). If you get this image from web server you should configure your web server to send appropriate headers to see SVGs properly.

In case if you use Jenkins then see this page for details: https://wiki.jenkins-ci.org/display/JENKINS/Configuring+Content+Security+Policy

**Comment by manuelpichler** [comment]
I am sorry, but this is something that must be solved in the CI setup and cannot be solved within PDepend
