### ISSUE TITLE
Lacking support for const visibility (PHP 7.1)

### ISSUE THREAD

**Issue by torkiljohnsen** [pdepend/pdepend#297]
Reposting from PHPMD:
https://github.com/phpmd/phpmd/issues/436

**Comment by kofan** [comment]
Is it going to be fixed some day or other?
Is this repository abandoned? There are no commits for more than 6 months already...

**Comment by niconoe-** [comment]
It would be a good thing to fix this...
This is not a feature, it is really a bug since PHP is now 7.1.8, which means the 9th version of PHP 7.1 and this is not fixed yet.

A hint may be the overloading of the parseMethodOrFieldDeclaration method in the 7.1 parser class, but I'm not sure about the guidelines on how to propose a modification here.

**Comment by eichie** [comment]
Hi, your changes works fine. But there are still problems on const definitions in interfaces.

**Comment by krewetka** [comment]
is there any chance it will be finished soon?  It is here since February and last release is almost a year old.

**Comment by kylekatarnls** [comment]
Hi, PHP 7.1 missing features is now the very next priority for PDepend, they are:
- Full support of void
- Symmetric array destructuring
- Class constant visibility
- Multi catch exception handling

And the first two are about to be merged.

**Comment by kylekatarnls** [comment]
Fixed in [2.6](https://github.com/pdepend/pdepend/releases/tag/2.6.0)
