### ISSUE TITLE
Require at least PHP 7.1

### ISSUE THREAD

**Issue by emirb** [pdepend/pdepend#343]

**Comment by KacerCZ** [comment]
I'd prefer targeting PHP 7.1.
Nullable types in PHP 7.1 are great and according to http://php.net/supported-versions.php active support for PHP 7.0 ends in two days.

**Comment by emirb** [comment]
Even better as it's support is ending in two days. I've updated the issue :-)

**Comment by garak** [comment]
php 7.1 is out of support, and php 7.2 is in "security fixes only".
I guess you should target php 7.3 for next major release

**Comment by kylekatarnls** [comment]
Requiring PHP 7.1 does not prevent to use PHPMD running PHP 7.3 or more. But if we require PHP 7.3 it prevents from using it with PHP 7.1. And it's not because PHP team stop maintaining a version than we should exclude everybody that still uses it.

As PHPMD tool can be ran in some multi-versions Travis tests or used for libraries, having a too narrow range of compatibility would be counter-productive.

**Comment by garak** [comment]
Releasing  new versione doesn't make old realeses disappear. So, you're not excluding anyone, you're just keeping pace with good softwares

**Comment by kylekatarnls** [comment]
First thing to be noted: the link was posted in 2017.

Then it's not really (at all) a users concern. An important concern for users is the compatibility with the last stable PHP language version, but as long as libraries are compatible with the PHP version you use, you don't care about the minimum version those libraries support.

Dropping PHP versions make no sense if you don't use the new features where it's relevant, for example use typing for every parameters and return, use arrow-functions in PHP 7.4 etc. and so for the consistency of projects, it implies global refactor. That's not just a number you change in your composer.json. And that's not the kind of huge work a small team like ours can decide lightly to start.

PHPMD has one more constraint, it analyse PHP codebase, and currently this analyse does not handle properly all features of PHP 7.2+. So requiring PHP 7.3 to run before implementing PHP 7.2+ features support, means you would need to have PHP 7.3 to run PHPMD but could not use more than PHP 7.1 level in your project to get a relevant result, it makes even less sense.

So requiring PHP 7.3 (and even 7.1) is still not the priority, while catching up the maintenance pause and supporting PHP 7.2+ features is way more important. Still I know the benefit, I use PHP 7.4 on my personal applications.

**Comment by tvbeek** [comment]
As team we decided (for both this project as PHPMD) to not change the minimum required PHP version until we create a new major version. Currently we are working to handle the new options for PHP 7.1/7.2/7.3/7.4. And we didn't yet have any concrete plan to create a new major version.

If we start with a new major version we will decide the minimum version to support. That can be PHP 7.3, 7.4, 8.0 or whatever version is supported on that moment. So to be honest I think that on this moment it doesn't really matter what we think that should be the new minimum required PHP version.

**Comment by garak** [comment]
But, again, raising php version requirements doesn't exclude anyone. You can't say that "you would need to use PHP 7.3 to run PDepend". That's simply not true

**Comment by kylekatarnls** [comment]
Of course if you truncate my sentence:

> you would need to have PHP 7.3 to run PDepend but could not use more than PHP 7.1 level in your project to get a relevant result

e.g. for the given new PDepend version that will drop PHP < 7.3: this hypothetical version 3.0 you suggest us to set to PHP 7.3 level. If we do so, PHP < 7.3 users would stay on PDepend 2.x and PHP >= 7.3 would be able to upgrade to 3.0, but they would still not be able to use it on their code base (as logically containing PHP 7.2+ features PDepend not yet support). That means 3.0 would be used by very few people, and we would still have to maintain 2.x until we implement missing language support.

Your feedback is welcome, but you need to understand such choices have consequence for a library project maintenance.

**Comment by garak** [comment]
That's also not true.
Releasing a major version does not prevent you from maintaining old versions.
After release of version 3, you can continue to work on version 2 and add any functionality that prevent users from using it with PHP 7.1 and 7.2, without the need of providing support for PHP 7.3 (because you're supporting it in version 3).
A possible side effect is a more clean code, since you don't need to use tricks to support different PHP behaviors (and, of course, you're free to exploit new PHP functionalities)

Let me clarify: I'm not telling that this is the best possible path, I'm just confuting your reasons to avoid it.

**Comment by kylekatarnls** [comment]
> After release of version 3, you can continue to work on version 2

That's exactly what I don't want to: writing bugfixes/features in PHP 7.3 then rewriting them in PHP 5.3 because we can't yet stop maintaining our version 2.

When you see big teams maintaining multiple versions in parallel, there is a lot of work behind. And while it may sounds like gaining time by not having the PHP 5 stuff to support, it may not worth it as we will also lose time in cherry-picking bugfixes from branch to the other + the PHP level adjustment for each commit we cherry-pick.

**Comment by garak** [comment]
I agree that this is a crucial point and I understand your fears.
I'd only point out that this would be probably not so hard for a reduced codebase. I did in similar contexts and I found myself with little work to do.
On the other hand, pushing new versions of PHP is a good thing for the ecosystem (see for example the regular reports made by Jordi Boggiano about it).
Ehi, even wordpress made that step! :wink:

**Comment by pimjansen** [comment]
7.1 is EOL? Why the hell would you want to support this? I agree that for the old code that was build for it, it should still be there but for future things it does not make sense at all?

**Comment by kylekatarnls** [comment]
EOL of 7.1 is a PHP team decision, its not a reason enough to drop it. The same way you don't stop supporting a browser the day it stop being maintained. We serve users. And its not up to PHP version EOL to decide if we stop providing support for users that still use this version. That choices belongs to the core team and does not affect users. The biggest impact of this choice is on the features delivery pace, and I ensure you (with the global insight we have on the project) that right now this impact would be negative, so for your own good guys, don't put pressure on such things, it won't make the library any better for you. If you want to participate, open our issues list and put your energy on things that actually matter.
