### ISSUE TITLE
Phar release missing for newer versions

### ISSUE THREAD

**Issue by SMillerDev** [pdepend/pdepend#364]
[The blog post about the latest release](https://pdepend.org/news/pdepend-2.5.0-released.html) mentions that PHAR files are the preferred way to install, I couldn't find any of 2.5.1 or 2.5.2 however. Did this recommendation change? Or is there a different way to download the PHAR files that I'm missing?

**Comment by emirb** [comment]
Since the project almost got abandoned (see https://github.com/pdepend/pdepend/issues/324 for discussion), website is not being updated, nor have the phar files been generated.
@manuelpichler Can we work on automating this process?

**Comment by SMillerDev** [comment]
If someone can provide me with the way phars are currently generated I'd be happy to make a PR with the required Travis changes.

**Comment by dohpaz42** [comment]
It looks like it's a fairly simple (albeit lengthy) process:

1. Clone the repository: `git clone https://github.com/pdepend/pdepend.git`
1. Initialize the `setup` submodule: `git submodule init`
1. Update the `setup` submodule: `git submodule update`
1. Build the phar: `ant -Dbundle:commons.srcdir.php=/path/to/php-source phar:phar`
1. Deploy the site: `ant -Dremote.shell.credentials=user@example.com -Dphar.sign.keyfile=/path/to/key/file -Dcommons.env=production deploy`
1. `...` # Go for a marathon run... seriously.
1. $$$

It looks like Manuel worked on the [Qafoo/build-commons](https://github.com/Qafoo/build-commons) repository, and pdepend heavily depends on it. Might be worth forking that into the pdepend organization as well given [Qafoo/build-commons](https://github.com/Qafoo/build-commons) looks abandoned as well.

Sources: 
1. https://github.com/pdepend/pdepend/blob/master/build.xml
1. https://github.com/Qafoo/build-commons/blob/754fd29adb0dfb951b61dc73edff97c2bb10736b/src/main/xml/package.xml
1. https://github.com/Qafoo/build-commons/blob/754fd29adb0dfb951b61dc73edff97c2bb10736b/src/main/xml/exts/phar.xml

That Qagoo/build-commons repository is HUGE and full of a lot of possibilities.

**Comment by dohpaz42** [comment]
I've done a deeper dive into how the [abc (ant-build-commons)](http://abc.tools.qafoo.com/index.html) works, and how it's set up through `pdepend`.

* In the project root, you can run `ant -p` to get the following list of targets:
```bash
Main targets:

 clean             ->  Removes all temporary artifacts from previous builds
 compile           ->  Performs a static syntax check of the project.
 deploy            ->  Starts a remote deployment of the project build
 initialize        ->  Initializes the project build environment.
 install           ->  Installs the project local.
 integration-test  ->  Runs all tests for the project.
 package           ->  Generates distributable packages of the project.
 profile           ->  Performs a profiling of the project application.
 site              ->  Generate a site for a single project.
 test              ->  Runs the unit tests for the project.
 validate          ->  Validates the project configuration.
 verify            ->  Verifies that the source is valid and meets quality criterias.
```
* You do not need to supply `-Dbundle:commons.srcdir.php=/path/to/php-source`; in fact, configuration can be overridden from `build.properties`.
* I would recommend running `ant` using [`-logger org.apache.tools.ant.NoBannerLogger`](https://ant.apache.org/manual/api/org/apache/tools/ant/NoBannerLogger.html) to make the output much easier to read and follow. Personally, I created a bash alias.
* `pdepend` depends on an old (4.8.36) version of `phpunit`†, which is not compatible with PHP 7.2.
* `phpmd` also doesn't seem to play nice with PHP 7.2. I thought that I would have to install PHP 5.6, but it turns out that most of the aforementioned tools†† are happy with PHP 7.1 (e.g., the default that comes with macOS High Sierra). 
* When I run `phpmd` manually (e.g., `/usr/local/bin/php -d memory_limit=1024M /usr/local/bin/phpmd . xml codesize,unusedcode,naming,design`) I get the following error: `No node found at index 0 in node of type: PDepend\Source\AST\ASTExpression` with an exit code of `1` regardless of my PHP version
* I am able to successfully run `ant package` using PHP 7.1 and/or 5.6.
  * By default, `ant package` generates a "snapshot"; run `ant -Drelease=true package` for a "release" version.
  * The phar will default to `../build/dist/phar-<version|snapshotDATE>.phar`
* It appears that `ant deploy` will handle uploading the new phar(s) to the website -- using ssh and what appears to be public key authentication
  * Use `remote.shell.credentials` to define the `user@host` specification

† The `phpunit.package.name` in the `build.properties` is what determines the `phpunit` version that gets installed. 
†† `phpmd` returns `Result 2` when running `ant verify` while using PHP 7.x and 5.6

If there are further questions about the process, I'd be more than happy to continue digging.

**Comment by kylekatarnls** [comment]
The website now refers to PHAR files available on GitHub and the documented preferred way is now composer installation.
