### ISSUE TITLE
Website is offline

### ISSUE THREAD

**Issue by jakzal** [pdepend/pdepend#371]
The http://pdepend.org/ website seems to be offline and the phar is no longer available for download.

re #324, is any of current maintainers interested in getting help with the project? 

I built the phar with humbug/box and could send a PR to replace the current system.

I also think it's time to drop PHP 5 support and make the project structure conforms to modern PHP practices. I'm ready to work on this too if there's anyone to merge the PRs.

Short term, I'll probably setup a fork of the project to publish phars with github releases. I need it for https://github.com/jakzal/phpqa.

**Comment by emirb** [comment]
pinging @manuelpichler 

Regarding #324 I got maintainer access to the repository in the meantime. Please, feel free to submit a PR to replace the current phar building system. 

I also agree it is time to drop website as a source of releases and use GitHub releases like any other project nowadays.

If we can do all of this on the main repo instead of creating another fork, that'd be great. Thanks for your contributions @jakzal!

**Comment by jakzal** [comment]
Great to hear. I'll submit a PR soon.

In the meantime I've published a working phar here https://github.com/jakzal/pdepend/releases/download/2.5.2-jakzal-0/pdepend.phar

**Comment by jakzal** [comment]
Seems there's a plague 😂 https://github.com/phpmd/phpmd/issues/603

**Comment by ravage84** [comment]
I officially started the search for a new team of maintaners for PHPMD (& PDepend). If anybody is interested write me an email, see my GitHub profile page.

**Comment by ravage84** [comment]
@jakzal please contact me through my mail, so I can send you an invitation. Your contributions are very welcome.

> is it necessary?

Actually, we can discuss this. But first things first.

**Comment by kylekatarnls** [comment]
Working on it: #378
