### ISSUE TITLE
specific exact php version requirement 

### ISSUE THREAD

**Issue by vaishalilodhi** [pdepend/pdepend#454]
## Description
Please update PHP version requirement of the package on https://packagist.org/packages/pdepend/pdepend for pdepend version 2.7.0 to php >=^7 or as it is required

**Comment by tvbeek** [comment]
Did you got any error on PHP 5.*? We run our test also on 5.3, 5.4, 5.5 and 5.6 but maybe we destroyed something.

It should still run on >5.3.7 (like it say on packagist)

**Comment by kylekatarnls** [comment]
Please follow the issue pattern many required informations are missing in this issue to understand why we should update version requirement:

[ ] PHP Depend version
[ ] PHP Version
[ ] Installation type
[ ] Operating System / Distribution & Version
[ ] Current Behavior
[ ] Expected Behavior
[ ] Steps To Reproduce

Please add all at once editing the original message and I will re-open this issue.

Thanks.
