### ISSUE TITLE
TooManyPublicMethods ignore exceptions

### ISSUE THREAD

**Issue by alexxxHorpah** [pdepend/pdepend#708]
- PHP Depend version: any (8.2 test)
- PHP Version: any (8.2.11 test)
- Installation type: composer
- Operating System / Distribution & Version: any (win10 test)

### Current Behavior
phpmd doesn't ignore classes added in config as _exceptions_

### Expected Behavior
phpmd should ignore classes added in config as _exceptions_

### Steps To Reproduce:
1) Add config:

```
....
<rule ref="rulesets/codesize.xml/TooManyPublicMethods">
        <properties>
            <property name="exceptions">
                <value>
                    NS\Some\ClassName
                </value>
            </property>
        </properties>
    </rule>
....
```
2) Create class  **NS\Some\ClassName** with 10+ public methods called method1, method2, .... method11
3) Run phpmd

## Checks before submitting
* [ ] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/pdepend/pdepend/issues)
* [ ] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/pdepend/pdepend/pulls)
* [ ] I have added every step to reproduce the bug.
* [ ] If possible I added relevant code examples.
* [ ] This issue is about 1 bug and nothing more.
* [ ] The issue has a descriptive title. For example:  "Default value is not available in AST when it's an array".

**Comment by kylekatarnls** [comment]
Hello,

I'm closing this because it is not handled by PDepend (which is the parsing engine), it lives on phpmd/phpmd.

At the moment this rule just does not have `exceptions` parameter as per documentation: https://phpmd.org/rules/codesize.html#toomanypublicmethods

It has only ignorepattern (which is not targeting class name but method name).

It's likely that we'll have a more consistent set of options across rules for the next major version of PHPMD (3.x), a discussion was in progress there:
https://github.com/phpmd/phpmd/issues/440

For the moment, the way to go is to add a `/** @SuppressWarning(TooManyPublicMethods) */` annotation in the PHPDoc of your class.

Thanks.
